/* Prospero Radio read-only USB audio bridge wire constants. */
/* Copyright (C) 2026 BlackBearReloaded */
/* SPDX-License-Identifier: GPL-3.0-or-later */

#ifndef PROSPERO_RADIO_USB_PROTOCOL_H
#define PROSPERO_RADIO_USB_PROTOCOL_H

#define RADIO_USB_HTTP_PORT 7003U
#define RADIO_USB_MAX_ENTRIES 128U
#define RADIO_USB_NAME_BYTES 111U
#define RADIO_USB_PATH_BYTES 512U
#define RADIO_USB_INDEX_VERSION 1U
#define RADIO_USB_INDEX_HEADER_BYTES 9U
#define RADIO_USB_INDEX_RECORD_FIXED_BYTES 14U
#define RADIO_USB_INDEX_MAX_BYTES 16384U
#define RADIO_USB_MEDIA_PENDING 4U
#define RADIO_USB_MEDIA_ERROR 5U
#define RADIO_USB_HEADER_DEVICE_AVAILABLE_OFFSET 8U

#define RADIO_USB_ENTRY_MP3 1U
#define RADIO_USB_ENTRY_AAC 2U
#define RADIO_USB_ENTRY_FLAC 3U
#define RADIO_USB_ENTRY_WAV 4U

#endif
