/* Prospero Radio USB optical-disc bridge wire constants. */
/* Copyright (C) 2026 BlackBearReloaded */
/* SPDX-License-Identifier: GPL-3.0-or-later */

#ifndef PROSPERO_RADIO_DISC_PROTOCOL_H
#define PROSPERO_RADIO_DISC_PROTOCOL_H

#define RADIO_DISC_DEVICE_PATH "/dev/cd1"
#define RADIO_DISC_MOUNT_PATH "/mnt/disc"
#define RADIO_DISC_HTTP_PORT 7002U
#define RADIO_DISC_MAX_ENTRIES 128U
#define RADIO_DISC_NAME_BYTES 111U
#define RADIO_DISC_INDEX_VERSION 2U
#define RADIO_DISC_INDEX_HEADER_BYTES 9U
#define RADIO_DISC_INDEX_RECORD_FIXED_BYTES 14U
#define RADIO_DISC_INDEX_MAX_BYTES 16384U
#define RADIO_DISC_MEDIA_PENDING 4U
#define RADIO_DISC_MEDIA_ERROR 5U
#define RADIO_DISC_HEADER_DEVICE_AVAILABLE_OFFSET 8U

#define RADIO_DISC_ENTRY_CDDA 1U
#define RADIO_DISC_ENTRY_MP3 2U
#define RADIO_DISC_ENTRY_AAC 3U
#define RADIO_DISC_ENTRY_FLAC 4U
#define RADIO_DISC_ENTRY_WAV 5U

#endif
